apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ms-movies
  namespace: prod
  labels:
    app: backend-ms-movies
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-ms-movies
  template:
    metadata:
      labels:
        app: backend-ms-movies
        version: "1.00"
    spec:
      containers:
        - name: backend-ms-movies
          image: zebolhd/qa-backend-ms-movies:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qa-config
            - secretRef:
                name: qa-secret
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-ms-movies
  namespace: prod
spec:
  selector:
    app: backend-ms-movies
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32500
  type: NodePort
